apiVersion: v1
data:
  DB_DATABASE: {{.Values.dbName}}
  DB_DATABASE_HOST: {{ .Release.Name }}-mysql-service
  DB_DATABASE_PORT_NUMBER: "3306"
  DB_DATABASE_USER: {{.Values.dbUser}}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datos-mysql
  namespace: {{.Values.namespace}}
