apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: weekly-ingress
   namespace: {{.Values.namespace}}
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{.Values.ingressClassName}}
  rules:
  - host: {{.Values.ingressHost}}
    http:
      paths:
      - path: "{{.Values.ingressPathLaravel}}"
        pathType: Exact 
        backend:
          service:
            name: {{ .Release.Name }}-laravel-service
            port:
              number: 8000
{{- if .Values.phpmyadminIsDeployed }}
      - path: "{{.Values.ingressPathPhpmyadmin}}"
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-phpmyadmin-service
            port:
              number: 8090 #80
{{- end}}