apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-cronjob
  namespace: {{.Values.namespace}}
spec:
  storageClassName: sc-laravel
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.cronjobPVCStorage}}
