apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  DB_DATABASE_PASSWORD: "{{.Values.dbPass}}"
  DB_ROOT_PASSWORD: "{{.Values.dbRootPass}}"