{{- if .Values.phpmyadminIsDeployed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-phpmyadmin-credentials
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  DB_DATABASE_PASSWORD: "{{.Values.dbPass}}"
  DB_ROOT_PASSWORD: "{{.Values.dbRootPass}}"
{{- end}}