apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  namespace: {{.Values.namespace}}
  labels:
     app: mysqlapp
spec:
  ports:
  - port: 3306
  selector:
     app: mysqlapp
