apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-laravel-service
  namespace: {{.Values.namespace}}
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    app: laravel
  ports:
    - port: 8000