{{- if .Values.phpmyadminIsDeployed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin-service
  namespace: {{.Values.namespace}}
  labels:
     app: phpmyadmin
spec:
  ports:
  - port: 80
  selector:
     app: phpmyadmin
{{- end}}