apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  namespace: laravel
spec:
  storageClassName: sc-laravel
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
